### PR TITLE
Fix crash when the support library is present but not used for a particular Activity

### LINKED ISSUE #176: Crash due to FragmentCompat not checking instance types
FragmentCompat doesn't validate that the Activity instance is a FragmentActivity from the support library before casting it as such:

https://gist.github.com/anonymous/755add0f0749df986e54

This was recently introduced by #156

### PR DESCRIPTION
**Pull request by jasta**
This is done by simply checking whether we have an instance of
FragmentActivity before taking the support library path.  The framework
path doesn't need this check since it's impossible that if we have an
Activity and we are on a sufficiently high API level that the Activity
doesn't have fragment support.

Closes #176

### CODE REVIEW

**Comment by jasta** [comment]
@rickbrew didn't properly test this in `stetho-sample` and it bit me :)

Should be a simple fix then we should be ready to roll the 1.1.1 release.

File: stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatUtil.java [hunk 1]
```diff
@@ -26,13 +26,20 @@ public static Object findFragmentForView(View view) {
   @Nullable
   private static Object findFragmentForViewInActivity(Activity activity, View view) {
     FragmentCompat supportLib = FragmentCompat.getSupportLibInstance();
-    if (supportLib != null) {
+
+    // Try the support library version if it is present and the activity is FragmentActivity.
+    if (supportLib != null &&
+        supportLib.getFragmentActivityClass() == activity.getClass()) {
```
Comment (rickbrew) [inline stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatUtil.java]: This should be an isAssignableFrom() call, not a == comparison between Class<?>'s, right?

Comment (jasta) [inline stetho/src/main/java/com/facebook/stetho/common/android/FragmentCompatUtil.java]: Oops
